#!/usr/bin/env bash
set -euo pipefail
usage() { echo "Usage: $0 prepare-source-release|prepare-final-assets --input DIR --version X.Y.Z --output DIR [--public-source-url URL]" >&2; exit 2; }
phase="${1:-}"; shift || true
input= output= version= public_url=
while [ "$#" -gt 0 ]; do case "$1" in --input) input="$2"; shift 2;; --output) output="$2"; shift 2;; --version) version="$2"; shift 2;; --public-source-url) public_url="$2"; shift 2;; *) usage;; esac; done
case "$version" in [0-9]*.[0-9]*.[0-9]*) ;; *) usage;; esac; [ -d "$input" ] && [ -n "$output" ] || usage
source="$(find "$input" -type f -name "proxor-$version.tar.gz" -print -quit)"; manifest="$(find "$input" -type f -name "proxor-$version.source-manifest" -print -quit)"
[ -n "$source" ] && [ -n "$manifest" ] || { echo 'verified source artifact is required' >&2; exit 1; }
sha="$(shasum -a 256 "$source" | awk '{print $1}')"; grep -qx "version=$version" "$manifest"; grep -qx "sha256=$sha" "$manifest"
mkdir -p "$output"; cp "$source" "$manifest" "$output/"
if [ "$phase" = prepare-source-release ]; then exit 0; fi
[ "$phase" = prepare-final-assets ] || usage
case "$public_url" in "https://github.com/Ogstra/proxor/releases/download/"*/"proxor-$version.tar.gz") ;; *) echo 'public source URL must be the attached release asset' >&2; exit 1;; esac
for required in '*-windows64.zip' '*-winget-x64.zip' '*.AppImage' '*.deb' '*.rpm' '*.flatpak'; do find "$input" -type f -name "$required" -print -quit | grep -q . || { echo "missing $required" >&2; exit 1; }; done
! find "$input" -type f \( -iname '*.msi' -o -iname '*.dmg' \) -print -quit | grep -q .
# Debug packages are build by-products of the RPM spec; the published symbols channel is
# the Windows symbols archive.
assets() { find "$input" -type f \( -name '*.zip' -o -name '*.AppImage' -o -name '*.deb' -o -name '*.rpm' -o -name '*.flatpak' \) ! -name '*-debuginfo-*' ! -name '*-debugsource-*' ! -name '*.src.rpm'; }
asset_names() { assets | while read -r asset; do basename "$asset"; done; }
# Only the files that become release assets have to be unique: the build artifacts
# also carry per-job intermediates that legitimately share a name.
duplicates="$(asset_names | sort | uniq -d)"
[ -z "$duplicates" ] || { printf 'duplicate release asset names:\n%s\n' "$duplicates" >&2; exit 1; }
winget="$(find "$input" -type f -name '*-winget-x64.zip' -print -quit)"; winget_sha="$(shasum -a 256 "$winget"|awk '{print $1}')"
tag="${public_url#https://github.com/Ogstra/proxor/releases/download/}"; tag="${tag%%/*}"
packaging/winget/render-manifest.sh --version "$version" --url "https://github.com/Ogstra/proxor/releases/download/$tag/proxor-$version-winget-x64.zip" --sha256 "$winget_sha" --output "$output/winget-manifests"
pkgbuild="$(find "$input" -type f -name PKGBUILD -print -quit)"; srcinfo="$(find "$input" -type f -name .SRCINFO -print -quit)"
# .SRCINFO is generated by makepkg, which only exists in the Arch container that built
# and validated the recipe, so the release reuses that artifact instead of re-rendering.
[ -n "$pkgbuild" ] && [ -n "$srcinfo" ] || { echo 'validated AUR recipe is required' >&2; exit 1; }
for recipe in "$pkgbuild" "$srcinfo"; do grep -Fq "$public_url" "$recipe" && grep -Fq "$sha" "$recipe"; done
# GitHub rejects a leading dot in an asset name and silently renames the upload to
# default.SRCINFO, so the recipe ships under a versioned name.
mkdir -p "$output/aur"; cp "$pkgbuild" "$output/aur/PKGBUILD"; cp "$srcinfo" "$output/aur/proxor-$version.SRCINFO"
assets | while read -r asset; do cp "$asset" "$output/"; done
test "$(find "$output" -type f \( -name '*.zip' -o -name '*.AppImage' -o -name '*.deb' -o -name '*.rpm' -o -name '*.flatpak' \) | wc -l)" -eq "$(asset_names | wc -l)"
(cd "$output" && find . -type f ! -name SHA256SUMS -print0 | sort -z | xargs -0 shasum -a 256 > SHA256SUMS && shasum -a 256 -c SHA256SUMS)
