#include <QtTest>

#include "platform/ResolvConf.hpp"

using namespace ProxorPlatform;

namespace {
    const char *kStub = R"(# This is /run/systemd/resolve/stub-resolv.conf managed by man:systemd-resolved(8).
# Do not edit.
#
# This file might be symlinked as /etc/resolv.conf. If you're looking at
# /etc/resolv.conf and seeing this text, you have followed the symlink.

nameserver 127.0.0.53
options edns0 trust-ad
search .
)";
    const char *kUplink = R"(# This is /run/systemd/resolve/resolv.conf managed by man:systemd-resolved(8).
# Do not edit.

nameserver 192.168.1.1
search lan
)";
} // namespace

class ResolvConfTest : public QObject {
    Q_OBJECT
private slots:
    void managedStub() { QCOMPARE(ClassifyResolvConf(kStub), ResolvConfKind::ManagedBySystemdResolved); }
    void managedUplink() { QCOMPARE(ClassifyResolvConf(kUplink), ResolvConfKind::ManagedBySystemdResolved); }
    void managedCrlf() {
        QCOMPARE(ClassifyResolvConf(QString(kUplink).replace("\n", "\r\n")), ResolvConfKind::ManagedBySystemdResolved);
    }
    void networkManager() {
        QCOMPARE(ClassifyResolvConf("# Generated by NetworkManager\nsearch lan\nnameserver 192.168.1.1\n"), ResolvConfKind::Other);
    }
    void resolvconfStub() {
        QCOMPARE(ClassifyResolvConf("# Generated by resolvconf\nnameserver 127.0.0.53\n"), ResolvConfKind::UnmanagedResolvedStub);
        QCOMPARE(ClassifyResolvConf("# Generated by resolvconf\nnameserver 127.0.0.54\n"), ResolvConfKind::UnmanagedResolvedStub);
        QCOMPARE(ClassifyResolvConf("nameserver   127.0.0.53  \n"), ResolvConfKind::UnmanagedResolvedStub);
    }
    void blankLineBeforeHeader() {
        QCOMPARE(ClassifyResolvConf("\n# This is managed by man:systemd-resolved(8).\nnameserver 192.168.1.1\n"), ResolvConfKind::Other);
        QCOMPARE(ClassifyResolvConf("\n# This is managed by man:systemd-resolved(8).\nnameserver 127.0.0.53\n"), ResolvConfKind::UnmanagedResolvedStub);
    }
    void notStub() {
        QCOMPARE(ClassifyResolvConf("# nameserver 127.0.0.53\nnameserver 1.1.1.1\n"), ResolvConfKind::Other);
        QCOMPARE(ClassifyResolvConf(""), ResolvConfKind::Other);
        QCOMPARE(ClassifyResolvConf("nameserver 127.0.0.530\n"), ResolvConfKind::Other);
    }
    void notices() {
        QVERIFY(DirectDnsResolvedNotice(ResolvConfKind::Other).isEmpty());
        const auto managed = DirectDnsResolvedNotice(ResolvConfKind::ManagedBySystemdResolved);
        QVERIFY(managed.startsWith("[DNS]"));
        const auto unmanaged = DirectDnsResolvedNotice(ResolvConfKind::UnmanagedResolvedStub);
        QVERIFY(unmanaged.startsWith("[Warning]"));
        QVERIFY(unmanaged.contains("/run/systemd/resolve/stub-resolv.conf"));
        QVERIFY(unmanaged.contains("Direct DNS"));
        QVERIFY(!DirectDnsNoticeIsWarning(ResolvConfKind::Other));
        QVERIFY(!DirectDnsNoticeIsWarning(ResolvConfKind::ManagedBySystemdResolved));
        QVERIFY(DirectDnsNoticeIsWarning(ResolvConfKind::UnmanagedResolvedStub));
    }
};

QTEST_GUILESS_MAIN(ResolvConfTest)
#include "resolv_conf_test.moc"
